#!/bin/bash
#
# Check if the laptop is plugged into AC power.
#
# Dependencies: coreutils, util-linux

readonly L_OPTS="help"
readonly S_OPTS="h"

readonly USAGE=$(
  cat <<END
SYNOPSIS
  $(basename "$0") [OPTION]...

DESCRIPTION
  Check if the laptop is plugged into AC power.

OPTIONS
  -h, --help
    display this help and exit
END
)

opts=$(getopt --options=${S_OPTS} --longoptions=${L_OPTS} --name "$0" -- "$@")
if (($? != 0)); then
  echo
  echo "${USAGE}"
  exit 1
fi

eval set -- "${opts}"

need_help=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${USAGE}"
  exit 0
fi

if (($# > 0)); then
  echo "No positional arguments are expected."
  echo
  echo "${USAGE}"
  exit 2
fi

if (($(</proc/sys/vm/laptop_mode) == 0)); then
  echo "plugged into AC power"
else
  echo "unplugged from AC power"
fi
