#!/bin/bash
#
# Check if the laptop is plugged into AC power.
#
# Dependencies: coreutils, util-linux

readonly L_OPTS="help"
readonly OPTS="h"

readonly CMD="${0##*/}"
readonly USAGE="${CMD} [OPTION]..."
readonly USAGE_ERR_MSG=$(
  cat <<END
Usage: ${USAGE}
Try '${CMD} --help' for more information.
END
)
readonly HELP=$(
  cat <<END
SYNOPSIS
  ${USAGE}

DESCRIPTION
  Check if the laptop is plugged into AC power.

OPTIONS
  -h, --help
    display this help and exit
END
)

opts=$(getopt --options=${OPTS} --longoptions=${L_OPTS} --name "${CMD}" -- "$@")
if (($? != 0)); then
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

eval set -- "${opts}"

need_help=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${HELP}"
  exit 0
fi

if (($# != 0)); then
  echo "${CMD}: expected 0 arguments; got $#"
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

if (($(</proc/sys/vm/laptop_mode) == 0)); then
  echo "plugged into AC power"
else
  echo "unplugged from AC power"
fi
