#!/bin/bash
#
# Browse processes and threads.
#
# Dependencies: less, psmisc

pstree --color age \
  --show-parents --show-pids \
  --thread-names \
  --uid-changes \
  --unicode \
  | less --RAW-CONTROL-CHARS
