#!/bin/bash
#
# Increase/decrease keyboard backlight.
#
# Dependencies: coreutils, dbus, grep, upower

readonly L_OPTS="help"
readonly OPTS="h"

readonly CMD="${0##*/}"
readonly USAGE="${CMD} [OPTION]... +|-"
readonly USAGE_ERR_MSG=$(
  cat <<END
Usage: ${USAGE}
Try '${CMD} --help' for more information.
END
)
readonly HELP=$(
  cat <<END
SYNOPSIS
  ${USAGE}

DESCRIPTION
  Increase (+) or decrease (-) keyboard backlight.

OPTIONS
  -h, --help
    display this help and exit
END
)

opts=$(getopt --options=${OPTS} --longoptions=${L_OPTS} --name "${CMD}" -- "$@")
if (($? != 0)); then
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

eval set -- "${opts}"

need_help=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${HELP}"
  exit 0
fi

if (($# != 1)) || [[ $1 != "+" && $1 != "-" ]]; then
  if (($# != 1)); then
    echo "${CMD}: expected 1 argument; got $#"
  else
    echo "${CMD}: expected '+' or '-'; got $1"
  fi
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

declare -ir min_brightness=0
declare -ir max_brightness=$(
  dbus-send --system --type=method_call --print-reply \
    --dest="org.freedesktop.UPower" \
    "/org/freedesktop/UPower/KbdBacklight" \
    "org.freedesktop.UPower.KbdBacklight.GetMaxBrightness" \
    | grep --only-matching --perl-regexp "int32 \K\d+"
)
declare -i brightness=$(
  dbus-send --system --type=method_call --print-reply \
    --dest="org.freedesktop.UPower" \
    "/org/freedesktop/UPower/KbdBacklight" \
    "org.freedesktop.UPower.KbdBacklight.GetBrightness" \
    | grep --only-matching --perl-regexp "int32 \K\d+"
)

if [[ $1 == "+" ]]; then
  ((brightness += 1))
else
  ((brightness -= 1))
fi

if ((brightness > max_brightness)); then
  brightness=max_brightness
elif ((brightness < min_brightness)); then
  brightness=min_brightness
fi

dbus-send --system --type=method_call \
  --dest="org.freedesktop.UPower" \
  "/org/freedesktop/UPower/KbdBacklight" \
  "org.freedesktop.UPower.KbdBacklight.SetBrightness" \
  "int32:${brightness}"
