#!/bin/bash
#
# Create a .tar.gz archive.
#
# Dependencies: coreutils, gzip, tar, util-linux

readonly L_OPTS="help"
readonly OPTS="h"

readonly CMD=$(basename "$0")
readonly USAGE="${CMD} [OPTION]... ARCHIVE FILE..."
readonly USAGE_ERR_MSG=$(
  cat <<END
Usage: ${USAGE}
Try '${CMD} --help' for more information.
END
)
readonly HELP=$(
  cat <<END
SYNOPSIS
  ${USAGE}

DESCRIPTION
  Create an ARCHIVE.tar.gz from FILEs.

OPTIONS
  -h, --help
    display this help and exit
END
)

opts=$(getopt --options=${OPTS} --longoptions=${L_OPTS} --name "${CMD}" -- "$@")
if (($? != 0)); then
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

eval set -- "${opts}"

need_help=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${HELP}"
  exit 0
fi

if (($# < 2)); then
  echo "${CMD}: expected at least 2 arguments; got $#"
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

tar --create --file "$1.tar.gz" --gzip --verbose "${@:2}"
