#!/bin/bash
#
# Run the command detached from the terminal.
#
# Dependencies: coreutils, util-linux

readonly L_OPTS="help"
readonly S_OPTS="h"

readonly USAGE=$(
  cat <<END
SYNOPSIS
  $(basename "$0") [OPTION]... COMMAND

DESCRIPTION
  Run COMMAND detached from the terminal.

OPTIONS
  -h, --help
    display this help and exit
END
)

opts=$(getopt --options=${S_OPTS} --longoptions=${L_OPTS} --name "$0" -- "$@")
if (($? != 0)); then
  echo
  echo "${USAGE}"
  exit 1
fi

eval set -- "${opts}"

need_help=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${USAGE}"
  exit 0
fi

if (($# < 1)); then
  echo "At least one positional argument is expected."
  echo
  echo "${USAGE}"
  exit 2
fi

nohup "$@" 2>/dev/null &
