#!/bin/bash
#
# Extract files from an optionally compressed tar archive.
#
# Dependencies: coreutils, tar, util-linux
# Optional dependencies: bzip2, gzip, lzip, lzop, ncompress, xz, zstd

set -o nounset -o pipefail

readonly L_OPTS="help"
readonly OPTS="h"

readonly CMD="${0##*/}"
readonly USAGE="${CMD} [OPTION]... ARCHIVE DIR"
readonly USAGE_ERR_MSG=$(
  cat <<END
Usage: ${USAGE}
Try '${CMD} --help' for more information.
END
)
readonly HELP=$(
  cat <<END
SYNOPSIS
  ${USAGE}

DESCRIPTION
  Extract files from a tarball named ARCHIVE to the directory DIR.
  Also decompress the archive if it has one of the following extensions:
    .bz .bz2 .tbz .tbz2 - bzip2
    .gz .taz .tgz       - gzip
    .lz                 - lzip
    .lzo                - lzop
    .Z                  - ncompress
    .lzma .tlz .txz .xz - xz
    .zst                - zstd
  The corresponding optional dependencies must be satisfied.

OPTIONS
  -h, --help
    display this help and exit
END
)

opts=$(getopt --options=${OPTS} --longoptions=${L_OPTS} --name "${CMD}" -- "$@")
if (($? != 0)); then
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

eval set -- "${opts}"

need_help=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${HELP}"
  exit 0
fi

if (($# != 2)); then
  echo "${CMD}: expected 2 arguments; got $#"
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

mkdir --parents "$2" \
  && tar --extract --file "$1" \
       --verbose \
       --directory "$2"
