#!/bin/bash
#
# List dependencies of the script.
#
# Dependencies: coreutils, grep, util-linux

set -o nounset -o pipefail

readonly L_OPTS="help,optional,version"
readonly OPTS="hoVv"

readonly CMD="${0##*/}"
readonly USAGE="${CMD} [OPTION]... FILE"
readonly USAGE_ERR_MSG=$(
  cat <<END
Usage: ${USAGE}
Try '${CMD} --help' for more information.
END
)
readonly VERSION_INFO=$(
  cat <<END
${CMD} (scripts) 1.0.0

This is free and unencumbered software released into the public domain.
For more information, please refer to <https://unlicense.org/>.
END
)
readonly HELP=$(
  cat <<END
SYNOPSIS
  ${USAGE}

DESCRIPTION
  List dependencies of the script FILE.

OPTIONS
  -h, --help
    display this help and exit
  -o, --optional
    list optional dependencies instead of the required
  -V, -v, --version
    display version and exit
END
)

opts=$(getopt --options=${OPTS} --longoptions=${L_OPTS} --name "${CMD}" -- "$@")
if (($? != 0)); then
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

eval set -- "${opts}"

need_help=false
need_optional=false
need_version=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    -o | --optional)
      need_optional=true
      shift
      ;;
    -V | -v | --version)
      need_version=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${HELP}"
  exit 0
fi

if [[ $need_version == true ]]; then
  echo "${VERSION_INFO}"
  exit 0
fi

if (($# != 1)); then
  echo "${CMD}: expected 1 argument; got $#"
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

prefix="# Dependencies:"
if [[ $need_optional == true ]]; then
  prefix="# Optional dependencies:"
fi

grep --only-match --perl-regexp "^${prefix}\s+\K.*" "$1" \
  | tr --squeeze-repeats ", " "\n"
