#!/bin/bash
#
# Translate the selected text into the specified language.
#
# Dependencies: coreutils, gawk, libnotify, sed, util-linux, wget, xsel

readonly URL="https://translate.googleapis.com/translate_a/single"

readonly L_OPTS="help"
readonly OPTS="h"

readonly CMD=$(basename "$0")
readonly USAGE="${CMD} [OPTION]... LANG"
readonly USAGE_ERR_MSG=$(
  cat <<END
Usage: ${USAGE}
Try '${CMD} --help' for more information.
END
)
readonly HELP=$(
  cat <<END
SYNOPSIS
  ${USAGE}

DESCRIPTION
  Translate the selected text into LANG. Possible LANG values: en, de, etc.
  See https://cloud.google.com/translate/docs/languages for a complete list.

OPTIONS
  -h, --help
    display this help and exit
END
)

opts=$(getopt --options=${OPTS} --longoptions=${L_OPTS} --name "${CMD}" -- "$@")
if (($? != 0)); then
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

eval set -- "${opts}"

need_help=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${HELP}"
  exit 0
fi

if (($# != 1)); then
  echo "${CMD}: expected 1 argument; got $#"
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

notify-send --icon=info "$(xsel --output)" \
  "$(wget --output-document="-" --quiet --user-agent="Mozilla/5.0" \
    "${URL}?client=gtx&sl=auto&tl=$1&dt=t&q=$(xsel -o | sed "s/[\"'<>]//g")" \
    | sed "s/,,,0]],,.*//g" \
    | awk -F'"' '{print $2}')"
