#!/bin/bash
#
# Extract files from a .tar archive.
#
# Dependencies: coreutils, tar, util-linux

readonly L_OPTS="help"
readonly OPTS="h"

readonly CMD=$(basename "$0")
readonly USAGE="${CMD} [OPTION]... ARCHIVE DIR"
readonly USAGE_ERR_MSG=$(
  cat <<END
Usage: ${USAGE}
Try '${CMD} --help' for more information.
END
)
readonly HELP=$(
  cat <<END
SYNOPSIS
  ${USAGE}

DESCRIPTION
  Extract files from the .tar archive ARCHIVE to the directory DIR.

OPTIONS
  -h, --help
    display this help and exit
END
)

opts=$(getopt --options=${OPTS} --longoptions=${L_OPTS} --name "${CMD}" -- "$@")
if (($? != 0)); then
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

eval set -- "${opts}"

need_help=false

while true; do
  case "$1" in
    -h | --help)
      need_help=true
      shift
      break
      ;;
    --)
      shift
      break
      ;;
  esac
done

if [[ $need_help == true ]]; then
  echo "${HELP}"
  exit 0
fi

if (($# != 2)); then
  echo "${CMD}: expected 2 arguments; got $#"
  echo "${USAGE_ERR_MSG}"
  exit 2
fi

tar --extract --file "$1" --directory "$2" --verbose
