#!/bin/bash
#
# Extract files from a .tar.gz archive.
#

if (($# != 2)); then
  echo "Usage: unpack_tar_gz_archive ARCHIVE DIR"
  exit 1
fi

tar --extract --file "$1" --gzip --directory "$2" --verbose
